### ISSUE TITLE
Not working after upgrading from Angular 8 to 9.1

### ISSUE THREAD

**Issue by mjohanss** [steveadoo32/ngx-signalr-hubservice#31]
Getting the following error after upgrade to Angular 9.1

> ngx-signalr-hubservice.js:79 Uncaught TypeError: Reflect.getMetadata is not a function
    at getOrCreateHubProperties (ngx-signalr-hubservice.js:79)
    at ngx-signalr-hubservice.js:117

**Comment by TobiasBreuer** [comment]
For anyone else reaching here: I had to update my polyfills.ts file to make this work:

```
/** Evergreen browsers require these. **/
import 'core-js/es/reflect';
import 'reflect-metadata';
```

The line `import 'core-js/es/reflect';` was required after upgrading angular to version 9
The line `import 'reflect-metadata';` was added by me afterwards to make hubservice work with angular 9

I'm now using these versions:

```
"@angular/core": "9.1.13",
"ngx-signalr-hubservice": "^9.0.1",
```
